AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'Formula/**/*'

# CLI tools have inherently complex command routing and operations
# These limits are relaxed from defaults but still maintain code quality

Metrics/ClassLength:
  Max: 500
  Exclude:
    - 'lib/macdev/environment.rb'
    - 'lib/macdev/manifest.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

# Boolean flags are common and acceptable for simple CLI flags
Style/OptionalBooleanParameter:
  Enabled: false
